# Generated by Django 2.1.6 on 2019-04-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_opt_out', '0002_auto_20171214_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optoutfeedbacktranslation',
            name='language',
            field=models.CharField(max_length=5),
        ),
    ]
